import "./globals.css";
import { Open_Sans } from 'next/font/google';
import localFont from 'next/font/local'
const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-openSans', 
  weight: ['300', '400', '500', '600', '700', '800']
});
const podcastFont = localFont ({
  src: './fonts/Podcast.otf',
  display:'swap'
})


export const metadata = {
  title: "Task-7",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${podcastFont.className}`}> 
        {children}
      </body>
    </html>
  );
}
